// <auto-generated />
namespace App2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class App2DBContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(App2DBContext));
        
        string IMigrationMetadata.Id
        {
            get { return "202003201151582_App2DBContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
